version: "1"

services: 
  cockroachdb:
    hostname: "cockroachdb"
    container_name: "cockroachdb"
    networks:
      - roachnet
    image: cockroachdb/cockroach:v22.2.8
    # restart: always
    ports:
      - 26257:26257
      - 5432:5432
      - 8080:8080
    volumes:
      - ./cockroach-data:/cockroach/cockroach-data
    command: bash -c "cockroach start-single-node --insecure "

  zookeeper:
    container_name: zookeeper
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    networks:
      - roachnet  
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    container_name: kafka
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9092:9092"
    networks:
      - roachnet  
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
    depends_on:
      - zookeeper  


networks:
  roachnet:
    driver: bridge
# bash -c "cockroach start --certs-dir=/certs --store=node1 --listen-addr=localhost:26257 --http-addr=localhost:8080 --sql-addr=cockroachdb:5432 --join=localhost:26257,localhost:26258,localhost:26259 --background"