Feature:

  Scenario Outline: Try To add Comapny With invalid syntex of input
    Given company details name:"<name>",address:"<address>",ownerName:"<ownerName>",ownerAddress:"<ownerAddress>",ownerMail:"<ownerMail>",ownerPassword:"<ownerPassword>",ownerPhoto:'<ownerPhoto>',contectNo:"<contectNo>",contectEmail:"<contectEmail>",isCorrectName:"<isCorrectName>"
    When try to add company
    Then it will throw an error with message:<message>
    And addcompanyDB function will be called :<addcompanyDBFunctionCallCount> while adding company
    And companyTemplet function will be called :<companyTempletFunctionCallCount> while adding company
    And addOwnerCall function will be called :<addOwnerCallFunctionCallCount> while adding company

    Examples:
      | name     | address      | ownerName | ownerAddress | ownerMail           | ownerPassword | ownerPhoto                                           | contectNo  | contectEmail   | isCorrectName | message                                                                                             | addcompanyDBFunctionCallCount | companyTempletFunctionCallCount | addOwnerCallFunctionCallCount |
      |          |              |           |              |                     |               |                                                      |            |                | 'false'       | '"name" is required'                                                                                | 0                             | 0                               | 0                             |
      | aa       |              |           |              |                     |               |                                                      |            |                | 'false'       | '"name" length must be at least 3 characters long'                                                  | 0                             | 0                               | 0                             |
      | Rapidops |              |           |              |                     |               |                                                      |            |                | 'true'        | '"address" is required'                                                                             | 0                             | 0                               | 0                             |
      | Rapidops | 0            |           |              |                     |               |                                                      |            |                | 'true'        | '"address" length must be at least 5 characters long'                                               | 0                             | 0                               | 0                             |
      | Rapidops | Stelite Road |           |              |                     |               |                                                      |            |                | 'true'        | '"ownerName" is required'                                                                           | 0                             | 0                               | 0                             |
      | Rapidops | Stelite Road | aa        |              |                     |               |                                                      |            |                | 'true'        | '"ownerName" length must be at least 3 characters long'                                             | 0                             | 0                               | 0                             |
      | Rapidops | Stelite Road | Vijay     |              |                     |               |                                                      |            |                | 'true'        | '"ownerAddress" is required'                                                                        | 0                             | 0                               | 0                             |
      | Rapidops | Stelite Road | Vijay     | aa           |                     |               |                                                      |            |                | 'true'        | '"ownerAddress" length must be at least 5 characters long'                                          | 0                             | 0                               | 0                             |
      | Rapidops | Stelite Road | Vijay     | Prahladnagr  |                     |               |                                                      |            |                | 'true'        | '"ownerMail" is required'                                                                           | 0                             | 0                               | 0                             |
      | Rapidops | Stelite Road | Vijay     | Prahladnagr  | aa                  |               |                                                      |            |                | 'true'        | '"ownerMail" must be a valid email'                                                                 | 0                             | 0                               | 0                             |
      | Rapidops | Stelite Road | Vijay     | Prahladnagr  | email.mail@mail.com |               |                                                      |            |                | 'true'        | '"ownerPassword" is required'                                                                       | 0                             | 0                               | 0                             |
      | Rapidops | Stelite Road | Vijay     | Prahladnagr  | email.mail@mail.com | ss            |                                                      |            |                | 'true'        | '"ownerPassword" with value "ss" fails to match the required pattern: /^(?=.*[A-Z])(?=.*[0-9]).*$/' | 0                             | 0                               | 0                             |
      | Rapidops | Stelite Road | Vijay     | Prahladnagr  | email.mail@mail.com | 123456afaA    |                                                      |            |                | 'true'        | '"ownerPhoto" is required'                                                                          | 0                             | 0                               | 0                             |
      | Rapidops | Stelite Road | Vijay     | Prahladnagr  | email.mail@mail.com | 123456afaA    | {"fileldName":"data"}                                |            |                | 'true'        | '"ownerPhoto.fieldname" is required'                                                                | 0                             | 0                               | 0                             |
      | Rapidops | Stelite Road | Vijay     | Prahladnagr  | email.mail@mail.com | 123456afaA    | {"fieldname":"data"}                                 |            |                | 'true'        | '"ownerPhoto.fieldname" must be [ownerPhoto]'                                                       | 0                             | 0                               | 0                             |
      | Rapidops | Stelite Road | Vijay     | Prahladnagr  | email.mail@mail.com | 123456afaA    | {"fieldname":"ownerPhoto"}                           |            |                | 'true'        | '"ownerPhoto.originalname" is required'                                                             | 0                             | 0                               | 0                             |
      #   | Rapidops | Stelite Roa |"Vijay"  |"Prahladnagr | "email.mail@mailcom |"123456afaA"  | {"fieldname":"ownerPhoto",originalname:'file.exe'} |            |                | 'true'        |                                                                                                     | 0                             | 0                               | 0                             |
      | Rapidops | Stelite Road | Vijay     | Prahladnagr  | email.mail@mail.com | 123456afaA    | {"fieldname":"ownerPhoto","originalname":"file.exe"} |            |                | 'true'        | '"contectNo" is required'                                                                           | 0                             | 0                               | 0                             |
      | Rapidops | Stelite Road | Vijay     | Prahladnagr  | email.mail@mail.com | 123456afaA    | {"fieldname":"ownerPhoto","originalname":"file.exe"} | sahgyus    |                | 'true'        | '"contectNo" must be a number'                                                                      | 0                             | 0                               | 0                             |
      | Rapidops | Stelite Road | Vijay     | Prahladnagr  | email.mail@mail.com | 123456afaA    | {"fieldname":"ownerPhoto","originalname":"file.exe"} | 9876543210 |                | 'true'        | '"contectEmail" is required'                                                                        | 0                             | 0                               | 0                             |
      | Rapidops | Stelite Road | Vijay     | Prahladnagr  | email.mail@mail.com | 123456afaA    | {"fieldname":"ownerPhoto","originalname":"file.exe"} | 9876543210 | asa            | 'true'        | '"contectEmail" must be a valid email'                                                              | 0                             | 0                               | 0                             |
      | Rapidops | Stelite Road | Vijay     | Prahladnagr  | email.mail@mail.com | 123456afaA    | {"fieldname":"ownerPhoto","originalname":"file.exe"} | 9876543210 | email2mail.com | 'true'        | '"contectEmail" must be a valid email'                                                              | 0                             | 0                               | 0                             |

  Scenario Outline: Try To add Comapny With already existing company Name
    Given company details name:"<name>",address:"<address>",ownerName:"<ownerName>",ownerAddress:"<ownerAddress>",ownerMail:"<ownerMail>",ownerPassword:"<ownerPassword>",ownerPhoto:'<ownerPhoto>',contectNo:"<contectNo>",contectEmail:"<contectEmail>",isCorrectName:"<isCorrectName>"
    When try to add company
    Then it will throw an error with message:<message>
    And companyTemplet function will be called :<companyTempletFunctionCallCount> while adding company
    And addOwnerCall function will be called :<addOwnerCallFunctionCallCount> while adding company

    Examples:
      | name      | address      | ownerName | ownerAddress | ownerMail           | ownerPassword | ownerPhoto                                           | contectNo  | contectEmail    | isCorrectName | message                                         | addcompanyDBFunctionCallCount | companyTempletFunctionCallCount | addOwnerCallFunctionCallCount |
      | Rapidops2 | Stelite Road | Vijay     | Prahladnagr  | email.mail@mail.com | 123456afaA    | {"fieldname":"ownerPhoto","originalname":"file.exe"} | 9876543210 | email2@mail.com | false         | "Key (company_name)=(Rapidops2) already exists" | 1                             | 1                               | 0                             |

  Scenario Outline: Try To add Comapny with correct details
    Given company details name:"<name>",address:"<address>",ownerName:"<ownerName>",ownerAddress:"<ownerAddress>",ownerMail:"<ownerMail>",ownerPassword:"<ownerPassword>",ownerPhoto:'<ownerPhoto>',contectNo:"<contectNo>",contectEmail:"<contectEmail>",isCorrectName:"<isCorrectName>"
    When try to add company
    Then it will give result with id:'<id>'
    And companyTemplet function will be called :<companyTempletFunctionCallCount> while adding company
    And addOwnerCall function will be called :<addOwnerCallFunctionCallCount> while adding company

    Examples:
      | name     | address      | ownerName | ownerAddress | ownerMail           | ownerPassword | ownerPhoto                                           | contectNo  | contectEmail    | isCorrectName | id                          | addcompanyDBFunctionCallCount | companyTempletFunctionCallCount | addOwnerCallFunctionCallCount |
      | Rapidops | Stelite Road | Vijay     | Prahladnagr  | email.mail@mail.com | 123456afaA    | {"fieldname":"ownerPhoto","originalname":"file.exe"} | 9876543210 | email2@mail.com | true          | {"id":"ycgyusgcyugcyugsac"} | 1                             | 1                               | 1                             |
